### ISSUE TITLE
Error when using own layout

### ISSUE THREAD

**Issue by SirWindfield** [Drombler/drombler-fx#126]
I wanted to customize the application layout by adding a status bar and using a NotificationPane from the controls-fx library as the content pane. I used the classic desktop layout as a base and only modified the parts that I wanted to change. The problem is that every time when I start my application, I get a NPE:
```
cd /Users/Sven/NetBeansProjects/voices/voices-application; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home "/Applications/NetBeans/NetBeans 8.1.app/Contents/Resources/NetBeans/java/maven/bin/mvn" org.codehaus.mojo:exec-maven-plugin:1.4.0:exec
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building voices-application 0.1-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.4.0:exec (default-cli) @ voices-application ---
Loaded /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/../libprism_es2.dylib from relative path
JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
Loaded /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/../libglass.dylib from relative path
Calling main(String[]) method
User dir: /Users/Sven/NetBeansProjects/voices/voices-application/target/userdir
Initializing JavaFX Application "Voices 0.1-SNAPSHOT" (800x600)...
Auto-deploy install: org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: org.apache.felix.framework:4.6.0
Initialized JavaFX Application "Voices 0.1-SNAPSHOT"
Starting JavaFX Application "Voices 0.1-SNAPSHOT"...
Loaded /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/../libjavafx_font.dylib from relative path
Started JavaFX Application "Voices 0.1-SNAPSHOT"
Starting OSGi Framework...
Loaded /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/ext/../libprism_common.dylib from relative path
contentpane is BorderPane@474f4555
2016-03-15 15:39:21 INFO org.drombler.acp.core.docking.spi.impl.DockingAreaHandler resolveDockingArea - Adding docking area: 'center'
2016-03-15 15:39:21 INFO org.drombler.acp.core.docking.spi.impl.DockingAreaHandler resolveDockingArea - Adding docking area: 'top'
2016-03-15 15:39:21 INFO org.drombler.acp.core.docking.spi.impl.DockingAreaHandler resolveDockingArea - Adding docking area: 'bottom'
2016-03-15 15:39:21 INFO org.drombler.acp.core.docking.spi.impl.DockingAreaHandler resolveDockingArea - Adding docking area: 'left'
2016-03-15 15:39:21 INFO org.drombler.acp.core.docking.spi.impl.DockingAreaHandler resolveDockingArea - Adding docking area: 'right'
ERROR: org.drombler.acp.drombler-acp-core-docking-spi (23): [org.drombler.acp.core.docking.spi.impl.ViewDockingHandler(14)] The activate method has thrown an exception
java.lang.NullPointerException
	at org.drombler.acp.core.docking.spi.impl.ViewDockingManager.<init>(ViewDockingManager.java:71)
	at org.drombler.acp.core.docking.spi.impl.ViewDockingHandler.activate(ViewDockingHandler.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:231)
	at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:39)
	at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:624)
	at org.apache.felix.scr.impl.helper.BaseMethod.invoke(BaseMethod.java:508)
	at org.apache.felix.scr.impl.helper.ActivateMethod.invoke(ActivateMethod.java:149)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:315)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:127)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:871)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:838)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:850)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:931)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:895)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1480)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1401)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:1210)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:1148)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1432)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4547)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3521)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:350)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:1003)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:992)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:134)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:1044)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:841)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:419)
	at org.apache.felix.scr.impl.config.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:376)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialize(BundleComponentActivator.java:172)
	at org.apache.felix.scr.impl.BundleComponentActivator.<init>(BundleComponentActivator.java:120)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:258)
	at org.apache.felix.scr.impl.Activator.access$000(Activator.java:45)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:185)
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:479)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:414)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:443)
	at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:913)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4531)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2169)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
ERROR: org.drombler.acp.drombler-acp-core-docking-spi (23): [org.drombler.acp.core.docking.spi.impl.ViewDockingHandler(14)] Failed creating the component instance; see log for reason
```
I would not ask if I had no clue what is going wrong. I just changed the BorderPane that gets returned by the ContentPaneProvider to my own. I didn't even start to implement the status bar. I attached the maven project that is responsible for setting the layout. Maybe I missed something or I misunderstood it wrong. I thought that I could change the layout independently from other components, meaning that I can use my own layout but still be able to use the default docking implementation and the five pre-configured locations (top, left, right, bottom, center).
[voices-ui-layout.zip](https://github.com/Drombler/drombler-fx/files/174117/voices-ui-layout.zip)

**Comment by puce77** [comment]
The project needs the following plugin to run:

```
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-scr-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-scr-scrdescriptor</id>
                        <goals>
                            <goal>scr</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by puce77** [comment]
It might be a race condition. I'll double-check what needs to be run on the JavaFX Application thread and what not necessarily.

**Comment by SirWindfield** [comment]
I am sorry that I am pestering you :) Thank you for your help.

**Comment by SirWindfield** [comment]
Is there a way to use this branch for my application?

**Comment by puce77** [comment]
I'm glad if user report bugs if they appear so we can fix them.

**Comment by puce77** [comment]
https://github.com/Drombler/drombler-acp/pull/17/files

**Comment by SirWindfield** [comment]
Is it enough if I re-download the jars from the maven central?

**Comment by puce77** [comment]
https://github.com/Drombler/drombler-fx/pull/127/files

**Comment by puce77** [comment]
Also remove the applicationExecutor from your ApplicationRootNodeProvider.

**Comment by puce77** [comment]
From the Javadoc of the [Node](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html) class:

> Node objects may be constructed and modified on any thread as long they are not yet attached to a Scene in a Window that is showing. An application must attach nodes to such a Scene or modify them on the JavaFX Application Thread.

**Comment by puce77** [comment]
Everything is now deployed to https://oss.sonatype.org/content/repositories/snapshots/
Add this repository as a proxy for snapshot dependencies to your Maven Repository Manager such as Nexus.
I'm not sure how quickly you'll see updated snapshots.

Please try it out tell us if this solve the issue.

**Comment by SirWindfield** [comment]
I am getting a maven error

**Comment by puce77** [comment]
It doesn't look like you're using a Maven Repository Manager such as Nexus, but are accessing http://repo.maven.apache.org directly.
It's a [Maven best practice to use a Maven Repository Manager](http://maven.apache.org/repository-management.html) and to use a [single repository group](http://books.sonatype.com/nexus-book/reference/config-maven.html#ex-maven-nexus-simple).

**Comment by puce77** [comment]
Yes, the maven plugin has been deployed, too: https://oss.sonatype.org/content/repositories/snapshots/org/drombler/fx/drombler-fx-maven-plugin/0.8-SNAPSHOT/

**Comment by SirWindfield** [comment]
I tried it with Nexus OOS. I am still getting errors on the drombler-fx-maven-plugin. I installed nexus and added a mirror to my maven configuration file to send all requests to nexus (like in the links you gave me) . Still, netbeans is giving me the error. Sorry to pester you with this problem but I don't know anyone who is using a repo manager.

**Comment by SirWindfield** [comment]
Looks like it was some problem with the proxy settings of our router... All works as intended. My layout gets loaded. Thank you!
