### ISSUE TITLE
Closing View: NullPointerException [sf#18]

### ISSUE THREAD

**Issue by puce77** [Drombler/drombler-fx#19]
**Reported by puce on 2013-05-30 17:19 UTC**
Application: 2 Views: one in center, one in bottom

When closing the view in the bottom area, a NullPointerException gets thrown:
java.lang.NullPointerException
	at org.drombler.fx.core.docking.impl.DockingSplitPane.removeDockingArea(DockingSplitPane.java:234)
	at org.drombler.fx.core.docking.impl.DockingSplitPane.removeDockingArea(DockingSplitPane.java:227)
	at org.drombler.fx.core.docking.impl.skin.DockingPaneSkin$DockingAreaChangeListener.onChanged(DockingPaneSkin.java:123)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:291)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:48)
	at com.sun.javafx.collections.ObservableListWrapper.callObservers(ObservableListWrapper.java:97)
	at com.sun.javafx.collections.ObservableListWrapper.remove(ObservableListWrapper.java:255)
	at org.drombler.fx.core.docking.impl.DockingAreaPane.removeDockable(DockingAreaPane.java:113)
	at org.drombler.fx.core.docking.impl.skin.DockingAreaPaneSkin$2.onChanged(DockingAreaPaneSkin.java:83)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:291)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:48)
	at com.sun.javafx.collections.ObservableListWrapper.callObservers(ObservableListWrapper.java:97)
	at com.sun.javafx.collections.ObservableListWrapper.remove(ObservableListWrapper.java:255)
	at com.sun.javafx.scene.control.behavior.TabPaneBehavior.closeTab(TabPaneBehavior.java:198)
	at com.sun.javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$2.handle(TabPaneSkin.java:916)
	at com.sun.javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$2.handle(TabPaneSkin.java:913)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:69)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:217)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:170)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:38)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:37)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:35)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:35)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:35)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:35)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:35)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:35)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:35)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:92)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:53)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:33)
	at javafx.event.Event.fireEvent(Event.java:171)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3328)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3168)
	at javafx.scene.Scene$MouseHandler.access$1900(Scene.java:3123)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1563)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2265)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:250)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:173)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:292)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:528)
	at com.sun.glass.ui.View.notifyMouse(View.java:922)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$100(WinApplication.java:29)
	at com.sun.glass.ui.win.WinApplication$3$1.run(WinApplication.java:73)
	at java.lang.Thread.run(Thread.java:722)

The shortPath contains the unknown (and unneeded?) part: ShortPathPart{position=40, inActualLevel=1, inOrientation=HORIZONTAL}

**Comment by puce77** [comment]
**Commented by puce on 2013-05-30 17:25 UTC**
The exception also gets thrown if the second view gets registered in top, but not if it gets registered in left, right or center.

**Comment by puce77** [comment]
**Updated by puce on 2013-05-30 22:59 UTC**
- **status**: open --> pending

**Comment by puce77** [comment]
**Updated by puce on 2013-06-16 20:58 UTC**
- **status**: pending --> closed
- **Milestone**: Unknown --> 0.2

**Comment by puce77** [comment]
**Updated by puce on 2013-07-11 22:13 UTC**
- **labels**: Docking Framework --> Docking
